### ISSUE TITLE
[suggestion] Use Luarocks variable naming conventions

### ISSUE THREAD

**Issue by rafauke** [Sheepolution/how-to-love#18]
Motivation: https://github.com/luarocks/lua-style-guide#variable-names

Would that be a good idea in your opinon @Sheepolution? Have a great day :)

I can propose a PR for chapters included in the repo.

**Comment by Sheepolution** [comment]
I feel like I follow this fairly well. What are some examples where this isn't the case?

**Comment by rafauke** [comment]
> I feel like I follow this fairly well. What are some examples where this isn't the case?

I was referring to use of camel case in chapter 17 (e.g. `currentFrame` vs `current_frame`). It's no big issue for me, I was just curious.

Btw, the whole tutorial is super cool and I am grateful for your work on that :+1:  :)

**Comment by rafauke** [comment]
After giviing it some thought I think it's irrelevant for the tutorial :)
